#include <cstdio>
#include <chrono>
#include <memory>
#include "glfw_window.h"
#include "input_queue.h"
#include "input_event.h"
#include <GLFW/glfw3.h>

// Forward declarations generated by Source Forest
@FORWARD_DECLS@

int main() {
    printf("=== Entelechy Game Engine ===\n");
    printf("Solution: @SOLUTION_NAME@\n\n");

    // Initialize modules
@INIT_CALLS@

    // Create window
    auto window = std::make_unique<Entelechy::GlfwWindow>();
    if (!window->create(800, 600, "Entelechy Window")) {
        printf("Failed to create window\n");
        return -1;
    }

    printf("Window created. Press ESC to close.\n\n");

    // Event loop with DeltaTime
    using Clock = std::chrono::high_resolution_clock;
    auto lastTime = Clock::now();

    while (!window->shouldClose()) {
        auto now = Clock::now();
        float dt = std::chrono::duration<float>(now - lastTime).count();
        lastTime = now;

        window->pollEvents();

        // Consume raw input
        for (const auto& e : Entelechy::InputQueue::instance().events()) {
            switch (e.type) {
                case Entelechy::RawInputEvent::KeyPress:
                    printf("[KeyPress] key=%d\n", e.keyCode);
                    if (e.keyCode == GLFW_KEY_ESCAPE) {
                        window->requestClose();
                    }
                    break;
                case Entelechy::RawInputEvent::KeyRelease:
                    printf("[KeyRelease] key=%d\n", e.keyCode);
                    break;
                case Entelechy::RawInputEvent::MouseMove:
                    printf("[MouseMove] x=%.1f y=%.1f\n", e.mx, e.my);
                    break;
                case Entelechy::RawInputEvent::MouseButtonPress:
                    printf("[MouseButtonPress] button=%d\n", e.mouseButton);
                    break;
                case Entelechy::RawInputEvent::MouseButtonRelease:
                    printf("[MouseButtonRelease] button=%d\n", e.mouseButton);
                    break;
                case Entelechy::RawInputEvent::WindowResize:
                    printf("[WindowResize] %dx%d\n", e.width, e.height);
                    break;
                case Entelechy::RawInputEvent::Close:
                    printf("[Close]\n");
                    break;
            }
        }
        Entelechy::InputQueue::instance().clear();
    }

    window->destroy();
    printf("\nWindow closed. Goodbye.\n");
    return 0;
}
