#include <cstdio>
#include <chrono>
#include <memory>
#include <algorithm>
#include "glfw_window.h"
#include "input_queue.h"
#include "input_event.h"
#include "log/log_macros.h"
#include "render/opengl_backend.h"
#include "imgui/imgui_manager.h"
#include "imgui/imgui_panels.h"
#include <GLFW/glfw3.h>

// Forward declarations generated by Source Forest
@FORWARD_DECLS@

int main() {
    LOG_INFO(Entelechy::LogCategories::kEngine, "=== Entelechy Game Engine ===");
    LOG_INFO(Entelechy::LogCategories::kEngine, "Solution: @SOLUTION_NAME@");

    // Initialize modules
@INIT_CALLS@

    // Initialize logger
    Entelechy::Logger::instance().init("logs/engine.log");

    // Create window with a size appropriate for the primary monitor.
    int winW, winH;
    Entelechy::GlfwWindow::getRecommendedWindowSize(winW, winH);

    auto window = std::make_unique<Entelechy::GlfwWindow>();
    if (!window->create(winW, winH, "Entelechy Window")) {
        LOG_ERROR(Entelechy::LogCategories::kWindow, "Failed to create window");
        return -1;
    }
    window->centerOnScreen();

    LOG_INFO(Entelechy::LogCategories::kWindow, "Window created. Press ESC to close.");

    // Initialize graphics backend
    auto render = std::make_unique<Entelechy::OpenGLBackend>(window.get());
    if (!render->init(nullptr)) {
        LOG_ERROR(Entelechy::LogCategories::kEngine, "Failed to initialize graphics backend");
        return -1;
    }

    // Initialize ImGui (requires OpenGL context + GLFW window)
    auto imgui = std::make_unique<Entelechy::ImGuiManager>();
    if (!imgui->init(window->getGlfwWindow())) {
        LOG_ERROR(Entelechy::LogCategories::kEngine, "Failed to initialize ImGui");
        return -1;
    }

    // Event loop with DeltaTime
    using Clock = std::chrono::high_resolution_clock;
    auto lastTime = Clock::now();

    float fps = 0.0f;
    float fpsTimer = 0.0f;
    int frameCount = 0;

    // Clear color shared between engine and ImGui debug panel
    float clearColor[4] = {0.15f, 0.17f, 0.13f, 1.0f};

    while (!window->shouldClose()) {
        auto now = Clock::now();
        float dt = std::chrono::duration<float>(now - lastTime).count();
        lastTime = now;

        // Clamp extreme delta times (e.g. after breakpoint)
        dt = std::clamp(dt, 0.0f, 0.1f);

        Entelechy::Logger::instance().flush();

        window->pollEvents();

        // Consume raw input
        for (const auto& e : Entelechy::InputQueue::instance().events()) {
            switch (e.type) {
                case Entelechy::RawInputEvent::KeyPress:
                    LOG_DEBUG(Entelechy::LogCategories::kInput, "KeyPress key=%d", e.keyCode);
                    if (e.keyCode == GLFW_KEY_ESCAPE) {
                        window->requestClose();
                    }
                    break;
                case Entelechy::RawInputEvent::KeyRelease:
                    LOG_DEBUG(Entelechy::LogCategories::kInput, "KeyRelease key=%d", e.keyCode);
                    break;
                case Entelechy::RawInputEvent::MouseMove:
                    LOG_DEBUG(Entelechy::LogCategories::kInput, "MouseMove x=%.1f y=%.1f", e.mx, e.my);
                    break;
                case Entelechy::RawInputEvent::MouseButtonPress:
                    LOG_DEBUG(Entelechy::LogCategories::kInput, "MouseButtonPress button=%d", e.mouseButton);
                    break;
                case Entelechy::RawInputEvent::MouseButtonRelease:
                    LOG_DEBUG(Entelechy::LogCategories::kInput, "MouseButtonRelease button=%d", e.mouseButton);
                    break;
                case Entelechy::RawInputEvent::WindowResize:
                    LOG_DEBUG(Entelechy::LogCategories::kWindow, "WindowResize %dx%d", e.width, e.height);
                    break;
                case Entelechy::RawInputEvent::Close:
                    LOG_DEBUG(Entelechy::LogCategories::kWindow, "Close");
                    break;
            }
        }
        Entelechy::InputQueue::instance().clear();

        // ===== ImGui: begin new frame =====
        imgui->newFrame();

        // ===== Build UI =====
        int currentW, currentH;
        window->getSize(currentW, currentH);

        Entelechy::WindowSizeRequest sizeRequest;
        Entelechy::buildDockSpace();
        Entelechy::buildDebugPanel(dt, fps, clearColor, currentW, currentH, sizeRequest);
        Entelechy::buildLogPanel();

        if (sizeRequest.requested) {
            if (sizeRequest.width < 0 || sizeRequest.height < 0) {
                // Fit-to-monitor sentinel: recompute recommended size.
                Entelechy::GlfwWindow::getRecommendedWindowSize(sizeRequest.width, sizeRequest.height);
            }
            window->setSize(sizeRequest.width, sizeRequest.height);
            window->centerOnScreen();
        }

        // ===== ImGui: generate draw data =====
        imgui->render();

        // ===== Render frame =====
        render->beginFrame();
        render->setClearColor(clearColor[0], clearColor[1], clearColor[2], clearColor[3]);
        render->clear();

        // TODO: draw 3D scene here (Phase 5)

        // ===== ImGui: submit draw data (overlay on top of 3D) =====
        imgui->renderDrawData();
        imgui->updatePlatformWindows();

        render->present();

        // ===== FPS counter =====
        fpsTimer += dt;
        frameCount++;
        if (fpsTimer >= 1.0f) {
            fps = static_cast<float>(frameCount);
            fpsTimer = 0.0f;
            frameCount = 0;
        }
    }

    // Shutdown order: ImGui first (uses GL context), then render, then window
    imgui->shutdown();
    render->shutdown();
    window->destroy();

    LOG_INFO(Entelechy::LogCategories::kEngine, "Window closed. Goodbye.");
    return 0;
}
