#include <cstdio>
#include "world.h"
#include "type_registry.h"
#include "agent_bridge.h"

// Forward declarations generated by Source Forest
@FORWARD_DECLS@

// External print helper (from CoreLib)
extern void printWorld(const World& world);

using Entelechy::TypeRegistry;
using Entelechy::AgentBridge;

int main() {
    printf("=== Entelechy Game Engine ===\n");
    printf("Solution: @SOLUTION_NAME@\n\n");

    // Initialize modules
@INIT_CALLS@

    // Minimal ECS demo
    World world;

    Entity e0 = world.spawn();
    Entity e1 = world.spawn();
    Entity e2 = world.spawn();

    world.m_positions[e0] = {0.0f, 0.0f};
    world.m_velocities[e0] = {1.0f, 2.0f};

    world.m_positions[e1] = {10.0f, 5.0f};
    world.m_velocities[e1] = {-1.0f, 0.0f};

    world.m_positions[e2] = {3.0f, 3.0f};
    world.m_velocities[e2] = {0.5f, 0.5f};

    printWorld(world);

    printf("Destroying Entity %u...\n\n", e1);
    world.destroy(e1);

    printWorld(world);

    Entity e3 = world.spawn();
    world.m_positions[e3] = {99.0f, 99.0f};
    world.m_velocities[e3] = {0.0f, 0.0f};

    printf("Spawned Entity %u (reused slot):\n\n", e3);
    printWorld(world);

    printf("valid(e0)=%s, valid(e1)=%s, valid(e2)=%s, valid(e3)=%s\n",
           world.valid(e0) ? "true" : "false",
           world.valid(e1) ? "true" : "false",
           world.valid(e2) ? "true" : "false",
           world.valid(e3) ? "true" : "false");

    // TypeRegistry demo
    printf("\n=== TypeRegistry ===\n");
    printf("Component count: %zu\n", TypeRegistry::instance().componentCount());
    printf("Components: %s\n\n", TypeRegistry::instance().listComponents().c_str());
    printf("Describe Position:\n%s\n\n", TypeRegistry::instance().describeComponent("Position").c_str());
    printf("Describe Velocity:\n%s\n\n", TypeRegistry::instance().describeComponent("Velocity").c_str());
    printf("Describe Health:\n%s\n\n", TypeRegistry::instance().describeComponent("Health").c_str());
    printf("Describe NameTag:\n%s\n", TypeRegistry::instance().describeComponent("NameTag").c_str());

    // Deterministic System Scheduler demo
    printf("\n=== Deterministic Step (3 frames, dt=1.0) ===\n");
    AgentBridge bridge;
    bridge.init();

    Entity b0 = bridge.m_world.spawn();
    Entity b1 = bridge.m_world.spawn();
    bridge.m_world.m_positions[b0] = {0.0f, 0.0f};
    bridge.m_world.m_velocities[b0] = {1.0f, 2.0f};
    bridge.m_world.m_positions[b1] = {10.0f, 5.0f};
    bridge.m_world.m_velocities[b1] = {-1.0f, 0.0f};

    for (int i = 0; i < 3; ++i) {
        printf("-- Frame %d --\n", i + 1);
        bridge.step(1.0f);
        printWorld(bridge.m_world);
    }

    // AgentBridge structured tools demo (Milestone 0.4)
    printf("\n=== AgentBridge Tools ===\n");

    std::string entities_json = bridge.queryEntities("Position");
    printf("queryEntities(Position): %s\n", entities_json.c_str());

    printf("getComponent(b0, Velocity): %s\n", bridge.getComponent(b0, "Velocity").c_str());

    std::string set_result = bridge.setComponent(b0, "Velocity", "{\"vx\":5.0,\"vy\":5.0}");
    printf("setComponent(b0, Velocity): %s\n", set_result.c_str());

    printf("getComponent(b0, Velocity) after set: %s\n", bridge.getComponent(b0, "Velocity").c_str());

    printf("\n-- Frame after set --\n");
    bridge.step(1.0f);
    printWorld(bridge.m_world);

    // ToolRegistry demo
    printf("\n=== ToolRegistry ===\n");
    printf("Tool count: %zu\n", Entelechy::ToolRegistry::instance().toolCount());
    printf("Tools: %s\n\n", Entelechy::ToolRegistry::instance().listTools().c_str());

    printf("Describe queryEntities:\n%s\n\n", Entelechy::ToolRegistry::instance().describeTool("queryEntities").c_str());

    std::string tool_result = bridge.callTool("queryEntities", "{\"comp_name\":\"Position\"}");
    printf("callTool(queryEntities): %s\n", tool_result.c_str());

    tool_result = bridge.callTool("getComponent", "{\"entity\":0,\"comp_name\":\"Velocity\"}");
    printf("callTool(getComponent): %s\n", tool_result.c_str());

    tool_result = bridge.callTool("setComponent", "{\"entity\":0,\"comp_name\":\"Velocity\",\"values\":{\"vx\":10.0,\"vy\":10.0}}");
    printf("callTool(setComponent): %s\n", tool_result.c_str());

    tool_result = bridge.callTool("stepWorld", "{\"dt\":1.0}");
    printf("callTool(stepWorld): %s\n", tool_result.c_str());

    printf("\n-- Frame after tool step --\n");
    printWorld(bridge.m_world);

    // ToolRegistry auto-registered tools via REFLECT_TOOL macro
    printf("\n=== Auto-registered Tools (REFLECT_TOOL) ===\n");
    printf("callTool(listTools): %s\n", Entelechy::ToolRegistry::instance().callTool("listTools", "{}").c_str());
    printf("callTool(describeTool, describeTool): %s\n", Entelechy::ToolRegistry::instance().callTool("describeTool", "{\"name\":\"describeTool\"}").c_str());
    printf("callTool(listComponents): %s\n", Entelechy::ToolRegistry::instance().callTool("listComponents", "{}").c_str());
    printf("callTool(describeComponent, Velocity): %s\n", Entelechy::ToolRegistry::instance().callTool("describeComponent", "{\"name\":\"Velocity\"}").c_str());

    return 0;
}
