#!/usr/bin/env python3
"""
gen_reflection.py -- Code generator for Entelechy reflection system

Scans C++ header files for REFLECT_COMPONENT macros and generates
component serialization helpers.

Usage:
    python scripts/tools/gen_reflection.py \
        --input _engine/source \
        --output _engine/source/generated/component_serialization.cpp
"""

import os
import re
import sys
import argparse
from pathlib import Path

COMPONENT_RE = re.compile(
    r'REFLECT_COMPONENT\s*\(\s*(\w+)\s*,\s*(.*?)\s*\)\s*;',
    re.DOTALL
)

FIELD_RE = re.compile(
    r'REG_FIELD\s*\(\s*(\w+)\s*,\s*(\w+)\s*,\s*(\w+)\s*\)'
)

COMPOSITE_FIELD_RE = re.compile(
    r'REG_COMPOSITE_FIELD\s*\(\s*(\w+)\s*,\s*(\w+)\s*,\s*(\w+)\s*\)'
)


def extract_components_from_file(filepath):
    """Extract REFLECT_COMPONENT declarations from a header file."""
    with open(filepath, 'r', encoding='utf-8') as f:
        content = f.read()

    components = []
    for match in COMPONENT_RE.finditer(content):
        name = match.group(1)
        fields_str = match.group(2)

        fields = []
        for fmatch in FIELD_RE.finditer(fields_str):
            fields.append({
                'struct': fmatch.group(1),
                'name': fmatch.group(2),
                'type': fmatch.group(3),
                'kind': 'atom'
            })
        for fmatch in COMPOSITE_FIELD_RE.finditer(fields_str):
            fields.append({
                'struct': fmatch.group(1),
                'name': fmatch.group(2),
                'type': fmatch.group(3),
                'kind': 'composite'
            })

        components.append({
            'name': name,
            'fields': fields
        })

    return components


def scan_directory(directory):
    """Recursively scan for .h files and extract components."""
    all_components = []
    for root, _, files in os.walk(directory):
        for fname in files:
            if fname.endswith('.h'):
                filepath = os.path.join(root, fname)
                comps = extract_components_from_file(filepath)
                all_components.extend(comps)
    return all_components


def generate_serialization(components):
    """Generate C++ serialization code."""
    lines = []
    lines.append('// Auto-generated by gen_reflection.py')
    lines.append('// Do not edit manually!')
    lines.append('')
    lines.append('#include "type_registry.h"')
    lines.append('#include "world.h"')
    lines.append('#include "component_array.h"')
    lines.append('#include "core/small_string.h"')
    lines.append('#include "core/string_format.h"')
    lines.append('#include "core/string_intern_pool.h"')
    lines.append('#include <cstdio>')
    lines.append('')
    lines.append('namespace Entelechy {')
    lines.append('namespace generated {')
    lines.append('')

    for comp in components:
        name = comp['name']

        # toJson
        lines.append(f'SmallString toJson(const {name}& comp) {{')
        lines.append('    SmallString json = "{";')
        lines.append('    bool first = true;')
        for field in comp['fields']:
            fname = field['name']
            ftype = field['type']
            if field['kind'] == 'atom':
                if ftype in ('f32', 'float'):
                    lines.append(f'    if (!first) json += ","; first = false;')
                    lines.append(f'    json += "\\"{fname}\\":";')
                    lines.append(f'    char buf[32]; toStringBuf(buf, sizeof(buf), comp.{fname}); json += buf;')
                elif ftype in ('i32', 'int'):
                    lines.append(f'    if (!first) json += ","; first = false;')
                    lines.append(f'    json += "\\"{fname}\\":";')
                    lines.append(f'    char buf[32]; toStringBuf(buf, sizeof(buf), comp.{fname}); json += buf;')
                elif ftype in ('u32', 'unsigned int'):
                    lines.append(f'    if (!first) json += ","; first = false;')
                    lines.append(f'    json += "\\"{fname}\\":";')
                    lines.append(f'    char buf[32]; toStringBuf(buf, sizeof(buf), comp.{fname}); json += buf;')
                elif ftype == 'bool':
                    lines.append(f'    if (!first) json += ","; first = false;')
                    lines.append(f'    json += "\\"{fname}\\":";')
                    lines.append(f'    json += comp.{fname} ? "true" : "false";')
                elif ftype == 'SmallString':
                    lines.append(f'    if (!first) json += ","; first = false;')
                    lines.append(f'    json += "\\"{fname}\\":\\"";')
                    lines.append(f'    json += comp.{fname}.c_str();')
                    lines.append(f'    json += "\\"";')
                elif ftype == 'StringId':
                    lines.append(f'    if (!first) json += ","; first = false;')
                    lines.append(f'    json += "\\"{fname}\\":\\"";')
                    lines.append(f'    const char* resolved = StringInternPool::instance().resolve(comp.{fname});')
                    lines.append(f'    json += resolved ? resolved : "<unresolved>";')
                    lines.append(f'    json += "\\"";')
                else:
                    lines.append(f'    // TODO: serialize {ftype} field {fname}')
            else:
                lines.append(f'    // TODO: serialize composite {ftype} field {fname}')
        lines.append('    json += "}";')
        lines.append('    return json;')
        lines.append('}')
        lines.append('')

    lines.append('} // namespace generated')
    lines.append('} // namespace Entelechy')
    lines.append('')

    return '\n'.join(lines)


def main():
    parser = argparse.ArgumentParser(description='Generate Entelechy reflection code')
    parser.add_argument('--input', '-i', required=True, help='Input directory to scan')
    parser.add_argument('--output', '-o', required=True, help='Output file path')
    args = parser.parse_args()

    components = scan_directory(args.input)
    print(f'Found {len(components)} reflected components')

    code = generate_serialization(components)

    output_path = Path(args.output)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    with open(output_path, 'w', encoding='utf-8') as f:
        f.write(code)

    print(f'Generated {output_path}')


if __name__ == '__main__':
    main()
